loading_gif_url = "https://drive.google.com/file/d/17Vd91bEUk-wWne1q5r1uYly0JOdsXQ-O/view?usp=sharing"  # Using forward slashes
pexels_api_key = "Yo7K8dSk4ORv09UsZGrHEXjzCZVVu1fyWjfRNFDDlsLcUlL8ct4gCiqI"
email = "gabaledisha@gmail.com"
password = "*******"
